####Parameterized PBS Script ####
#PBS -A tgen-204000
#PBS -S /bin/bash
#PBS -l nodes=1
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -V
#PBS -o ${HOME}/jobOuts/parallelize_tophat/${PBS_JOBNAME}.${PBS_JOBID}.o
#PBS -M jcorneveaux@tgen.org
#PBS -m abe

cd $PBS_O_WORKDIR

START=$(date +%s)

#### OLD WILL DELETE ITS GROSS AND I THINK I HAVE A BETTER WAY ####
# 1M read splits for now..
#FQLINES=4000000
#READSPLIT=`echo "$FQLINES / 4" | bc`

#FQLINES=`zcat ${FQ1} | wc -l`
#READ_COUNT=`echo "$FQLINES / 4" | bc`

#echo "We have ${READ_COUNT} paired reads to split"

#READS_PER_NODE=`printf "%.0f" $(echo "${READ_COUNT} / ${NODE_COUNT}" | bc)`

#READS_PER_SPLIT=`echo "$READ_COUNT * 4" | bc`

#echo "We are splitting fastqs to $READS_PER_SPLIT  reads/job"

#echo -ne "\n`date` splitting ${FQ1} & ${FQ2} begun in ${PWD}\n\n"

#### OLD WILL DELETE ITS GROSS AND I THINK I HAVE A BETTER WAY ####

FQLINES=`zcat ${FQ1} | wc -l`
READ_COUNT=`zcat ${FQ1} | wc -l`

echo "We have ${READ_COUNT} paired reads to split"

READS_PER_NODE=`echo "${READ_COUNT} / ${NODE_COUNT}" | bc`

LINES_EACH=`echo "${READS_PER_NODE} / 4" | bc`

LINES_EACH=`printf "%.0f" ${LINES_EACH}`

READS_PER_SPLIT=`echo "${LINES_EACH} * 4" | bc`

echo "We are splitting fastqs to $READS_PER_SPLIT reads/job"

echo -ne "\n`date` splitting ${FQ1} & ${FQ2} begun in ${PWD}\n"

zcat ${FQ1} | split -a 3 -d -l ${READS_PER_SPLIT} - R1 &
zcat ${FQ2} | split -a 3 -d -l ${READS_PER_SPLIT} - R2 &

wait

## ADD A CHECK TO MAKE SURE WE DONT HAVE FILES WITH SMALL N reads MAKING PICARD FAIL ##
## Because we're nice like that ##

LASTFILE=`ls -1b R1* | tail -1`
SecLASTFILE=`ls -1b R1* | tail -2 | head -1`
LINES_LAST=`wc -l $LASTFILE | awk '{print$1}'`

READ2LAST=`echo $LASTFILE | sed -e 's/R1/R2/g'`
SecREAD2LAST=`echo $SecLASTFILE | sed -e 's/R1/R2/g'`

if [ $LINES_LAST -le 10000 ]; then
	cat $LASTFILE >> $SecLASTFILE
	cat $READ2LAST >> $SecREAD2LAST
	rm $LASTFILE
	rm $READ2LAST
fi

# Sanity check - should result in NODE_COUNT
SPLITS=`echo "${READ_COUNT} / ${READS_PER_SPLIT}" | bc`

echo -ne "\nThere are ${READ_COUNT} paired reads into ${SPLITS} for $READS_PER_SPLIT / fastq "
echo -ne "\nThere are ${READ_COUNT} paired reads into ${SPLITS} for $READS_PER_SPLIT / fastq \n\n" >> ${JOB_PATH}/jobLogs/${SAMPLE_ID}.cron.log

ls R1* | grep -v sai | sed -e 's/R1//g' > ~/SCRIPTS/parallelize_tophat/tophat2/messages/${SAMPLE_ID}.suffs.txt

echo -ne "\nsplitting fastqs took `bash ~/SCRIPTS/parallelize_tophat/tophat2/TimeOut.sh ${START}`\n\n"
echo -ne "\nsplitting fastqs took `bash ~/SCRIPTS/parallelize_tophat/tophat2/TimeOut.sh ${START}`\n\n" >> ${JOB_PATH}/jobLogs/${SAMPLE_ID}.cron.log
