####Parameterized PBS Script ####
#PBS -A tgen-204000
#PBS -S /bin/bash
#PBS -l nodes=1
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -V
#PBS -o ${HOME}/jobOuts/${PBS_JOBNAME}.${PBS_JOBID}.o
#PBS -M jcorneveaux@tgen.org
#PBS -m abe

cd $PBS_O_WORKDIR

START=$(date +%s)

# 1M read splits for now..
#FQLINES=4000000
#READSPLIT=`echo "$FQLINES / 4" | bc`

FQLINES=`zcat ${FQ1} | wc -l`
READ_COUNT=`echo "$FQLINES / 4" | bc`

echo "We have ${READ_COUNT} paired reads to split"

READS_PER_NODE=`printf "%.0f" $(echo "${READ_COUNT} / ${NODE_COUNT}" | bc)`

READS_PER_SPLIT=`echo $READ_COUNT * 4`

echo "We are splitting fastqs to $READS_PER_SPLIT  reads/job"

echo -ne "\n`date` splitting ${FQ1} & ${FQ2} begun in ${PWD}\n\n"

zcat ${FQ1} | split -a 3 -d -l ${READS_PER_SPLIT} - R1 &
zcat ${FQ2} | split -a 3 -d -l ${READS_PER_SPLIT} - R2 &

wait

echo -ne "\n\nSplits done, just counting now "
bash ~/SCRIPTS/TimeOut.sh ${START}

SPLITS=`echo "${READ_COUNT} / ${READS_PER_SPLIT}" | bc`

echo -ne "\n\nGetting read count complete `bash ~/SCRIPTS/TimeOut.sh ${START}`"

echo -ne "\nThere are ${READ_COUNT} paired reads into ${SPLITS} for $READS_PER_SPLIT / fastq "
echo -ne "\nThere are ${READ_COUNT} paired reads into ${SPLITS} for $READS_PER_SPLIT / fastq \n\n" >> ${JOB_PATH}/${SAMPLE_ID}.cron.log

ls R1* | grep -v sai | sed -e 's/R1//g' > ~/SCRIPTS/parallelize_tophat/tophat2/messages/${SAMPLE_ID}.suffs.txt


bash ~/SCRIPTS/TimeOut.sh ${START}
